<a href="https://colab.research.google.com/github/rattapornsupama/DPDM65/blob/main/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [239]:
import pandas as pd   
import matplotlib.pyplot as plt
import numpy as np

# import ไฟล์

In [240]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [241]:
 data = pd.read_csv('/content/drive/MyDrive/DPDM65/additional_data_newhouse.csv')

In [242]:
data.head()

,Unnamed: 0,id,parent_id,project_name,province,district,sub_district,zip_code,zone_id,zone,...,cable_range,cable_min,cable_max,cable_free,cable_none,cable_ask,position_previous,position_current,sold_out_at,is_pro_in_house
0,0,314.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
1,1,315.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
2,2,316.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
3,3,317.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
4,4,318.0,41.0,ที สเปซ กลางเมือง,ขอนแก่น,เมืองขอนแก่น,เมืองเก่า,NaN,5.0,กลางเมือง-เมืองเก่า-กุดกว้าง,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0

#เตรียมข้อมูล

เปลี่ยน error ทั้งหมดใน แต่ละคอลัมน์ที่เราที่เราสนใจ ให้เป็น ตัวเลข

In [243]:
data['usable_area'] = pd.to_numeric(data['usable_area'],errors='coerce')
data['number_of_story'] = pd.to_numeric(data['number_of_story'],errors='coerce')
data['number_of_bedroom'] = pd.to_numeric(data['number_of_bedroom'],errors='coerce')
data['number_of_bathroom'] = pd.to_numeric(data['number_of_bedroom'],errors='coerce')
data['number_of_parking'] = pd.to_numeric(data['number_of_bedroom'],errors='coerce')
#data['sell_price'] = pd.to_numeric(data['sell_price'],errors='coerce')

สร้างตารางข้อมูลใหม่ โดยเอามาเฉพาะคอลัมน์ที่เราสนใจ

In [244]:
data1=data[['usable_area','number_of_story','number_of_bedroom','number_of_bathroom','number_of_parking','sell_price']]
data1

,usable_area,number_of_story,number_of_bedroom,number_of_bathroom,number_of_parking,sell_price
0,185.0,2.0,4.0,4.0,4.0,3950000.0
1,165.0,2.0,4.0,4.0,4.0,3250000.0
2,260.0,2.0,4.0,4.0,4.0,6300000.0
3,343.0,2.0,6.0,6.0,6.0,6900000.0
4,223.0,2.0,4.0,4.0,4.0,4490000.0
...,...,...,...,...,...,...
988,120.0,1.0,3.0,3.0,3.0,1990000.0
989,96.0,1.0,2.0,2.0,2.0,1390000.0
990,100.0,1.0,3.0,3.0,3.0,1990000.0
991,NaN,2.0,2.0,2.0,2.0,1850000.0
992,138.0,1.0,3.0,3.0,3.0,2490000.0

เติมค่า missing ด้วย 0

In [245]:
data1 = data1.fillna(0)

ใช้ .dtypes  เพื่อดูลักษณะของข้อมูลว่าเป็น int , float , obj

In [246]:
data1.dtypes

usable_area           float64
number_of_story       float64
number_of_bedroom     float64
number_of_bathroom    float64
number_of_parking     float64
sell_price            float64
dtype: object

เช็คว่า ในข้อมูลที่เราสนใจ มีค่าใดเป็น NaN หรือไม่


*   ถ้ามี จะตอบกลับเป็น True
*   ถ้าไม่มี จะตอบกลับเป็น False

In [247]:
np.any(np.isnan(data1))

False

เช็คว่า ในข้อมูลที่เราสนใจ มีค่าใดเป็น finite หรือไม่


*   ถ้ามี จะตอบกลับเป็น True
*   ถ้าไม่มี จะตอบกลับเป็น False

In [248]:
np.all(np.isfinite(data1)) #and gets Truee

True

ใช้ .corr() เพื่อดูค่า correlation
- หากค่าเป็นบวก จะบ่งบอกถึงว่าเมื่อ x เพิ่ม y ก็มีแนวโน้มจะเพิ่มด้วย
- หากเป็นลบ หมายถึงว่าเมื่อ x เพิ่ม y ก็มีแนวโน้มจะลด
- แต่ถ้าเป็น 0 นั่นหมายความว่าไม่ว่า x จะเพิ่มหรือลดยังไงก็ไม่อาจบอกได้ว่า y จะเพิ่มหรือว่าลด
---
สหสัมพันธ์จะมีค่าจะอยู่ระหว่าง -1 ถึง 1 เสมอ

โดยถ้าสหสัมพันธ์เป็น 1 แสดงว่า x ∝ y โดยสมบูรณ์ ถ้าเป็น -1 หมายถึง x ∝ -y

In [249]:
data1.corr()

,usable_area,number_of_story,number_of_bedroom,number_of_bathroom,number_of_parking,sell_price
usable_area,1.000000,0.393332,0.523473,0.523473,0.523473,0.586450
number_of_story,0.393332,1.000000,0.545687,0.545687,0.545687,0.352649
number_of_bedroom,0.523473,0.545687,1.000000,1.000000,1.000000,0.424731
number_of_bathroom,0.523473,0.545687,1.000000,1.000000,1.000000,0.424731
number_of_parking,0.523473,0.545687,1.000000,1.000000,1.000000,0.424731
sell_price,0.586450,0.352649,0.424731,0.424731,0.424731,1.000000

# Linear Regression

In [250]:
from sklearn.linear_model import LinearRegression

X คือ feature ที่เราสนใจ

y คือ sell_price

In [251]:
X = data1[['usable_area','number_of_story','number_of_bedroom','number_of_bathroom','number_of_parking']]
y = data1['sell_price']

In [252]:
lrm = LinearRegression()
lrm.fit(X, y)

LinearRegression()

In [253]:
predictions = lrm.predict(X)
predictions

array([ 4624924.25938116,  4334245.87149058,  5714968.21397085,
        7550182.18598914,  5177213.19637327,  5496959.42305291,
        4450517.22664681,  4247042.3551234 ,  3336702.32881152,
        4247042.3551234 ,  3336702.32881152,  2764208.31738373,
        4991838.11305431,  8721758.50190485,  4237805.33127233,
        4237805.33127233,  5278950.63213497,  3612846.79730758,
        1261917.72420378,  1261917.72420378,  1261917.72420378,
        1261917.72420378,  1261917.72420378,  1307250.50912089,
        2860648.85760198,  3947126.94338174,  3223996.84246521,
        3558276.98853938,  5758569.97215443,  2964117.32009722,
        3078657.64851992,  1621699.84025708,  6610774.3208882 ,
        4988272.24424439,  4092466.13732704,  4988272.24424439,
        1261917.72420378,  2255521.13857521,  2933318.45457463,
        3151327.24549257,  3511109.36154587,  3947126.94338174,
         680186.68892491,   738322.36650303,   854593.72165926,
        1387051.84371339,  1314382.24674074,  1145272.10954985,
         927263.31863191,  4306909.05943505,  4888265.83521621,
         665652.76953039,   709254.52771397,  5400518.88283466,
        4528483.71916291,  4842933.0502991 ,  4383144.52521762,
        4237805.33127233,  3656448.55549116,   796458.04408115,
         723788.4471085 ,  4426746.28340121,  5051704.81736596,
        5613230.77820914,  5031874.00242798,  4639458.17877569,
        3947126.94338174,  4092466.13732704,   273236.9458781 ,
         947468.39306759,  4604719.18494548,  1576367.05533997,
        1261917.72420378,   947468.39306759,  1936149.17139327,
        1621699.84025708,  1261917.72420378,  3078657.64851992,
        3078657.64851992,  2313656.81615333,  3064123.72912539,
        3442005.63338315,  5255179.68888937,  2833312.04554645,
        4165135.73429968,  4746492.51008085,  2179285.67279264,
        1863105.31492293,  1892173.15371199,  2037512.34765728,
        2037512.34765728,  4784797.37272098,  3027549.89321879,
        1621699.84025708,  1621699.84025708,  1936149.17139327,
        2905981.6425191 ,  3180395.08428163,  3729118.15246381,
        4383144.52521762,  4673822.9131082 ,  4621358.39057124,
        4092466.13732704,  5506196.44690399,  2328190.73554786,
        3442005.63338315,  2400860.3325205 ,  1261917.72420378,
        5255179.68888937,  4595856.4205921 ,  3514675.2303558 ,
        4833696.02644802,  4543017.63855744,  2429928.17130956,
        3563948.14358053,  3040352.78587979,  4116237.08057264,
        4077932.21793251,  4552254.66240852,  4755729.53393192,
        4528483.71916291,  7115521.3713891 ,  8926964.40016179,
        3919790.13132621,  6239920.33890742,  1645096.52400499,
        2789710.28736287,  3656448.55549116,  1357984.00492433,
        1488789.27947509,  1663196.31220944,  1881205.10312738,
        3278566.6512334 ,  3685516.39428022,  4005262.62095986,
        4450517.22664681,  4595856.4205921 ,  3787253.83004192,
        4406915.46846323,  2973354.34394829,  3869160.45086565,
        3569245.03912399,  3467507.60336228,  3941830.04783829,
        3656448.55549116,  4130770.99996717,  4203440.59693982,
        4528483.71916291,  3412937.79459409,  2991454.13215275,
        4872000.88908816,  1621699.84025708,  3249498.81244435,
        4305178.03270152,  3903525.18519816,  4223271.4118778 ,
        4310474.92824497,  3772719.9106474 ,  4310474.92824497,
        3772719.9106474 ,   781924.12468662,   592983.17255774,
         738322.36650303,  1169043.05279545,   651118.85013586,
         709254.52771397,   781924.12468662,   680186.68892491,
        2524637.68479429,  3641914.63609663,  4421449.38785775,
         636584.93074133,   636584.93074133,  1314382.24674074,
         738322.36650303,   767390.20529209,  1081839.53642828,
        1261917.72420378,  3801787.74943645,  7459038.54131434,
        5807468.62588147,  7880522.20375569,  5240645.76949484,
        4717424.67129179,  4494118.9848304 ,  3772719.9106474 ,
        3554711.11972946,  2691538.72041109,  2760642.44857381,
        3511109.36154587,  2715309.66365669,   947468.39306759,
        1621699.84025708,  9008871.02098551,  6427130.26430278,
        4528483.71916291,   694720.60831944,   767390.20529209,
        1198110.89158451,  1445187.52129151,  4673822.9131082 ,
        4063398.29853798,  3874457.3464091 ,  1674164.36279405,
        1936149.17139327,  1936149.17139327,  1261917.72420378,
        4363313.71027964,  2904250.61578557,  3859923.42701457,
        2758911.42184028,  5714968.21397085,  4383144.52521762,
        3442005.63338315,  3442005.63338315,  1261917.72420378,
        2817047.0994184 ,  2817047.0994184 ,  3365770.16760058,
        3511109.36154587,  4043567.4836    ,  2962386.29336369,
         947468.39306759,  2110181.94462992,  2787979.26062934,
        3035055.89033633,   947468.39306759,   947468.39306759,
         423873.03536684,  1285314.40795169,  1343450.0855298 ,
        1145272.10954985,  3438439.76457323,  3278566.6512334 ,
        4107000.05672157,  4799331.29211551,  3394838.00638964,
        3656448.55549116,  3801787.74943645,  4107000.05672157,
        3394838.00638964,  3641914.63609663,  3801787.74943645,
        3903525.18519816,  4479585.06543587,  4799331.29211551,
        5031874.00242798,  5322552.39031856,  5676663.35133071,
        3307634.49002246,  2775176.36796834,  2962386.29336369,
        3878023.21521902,  6005646.60186143,  2404426.20133043,
        1605060.63463133,   927263.31863191,   467474.79355043,
         438406.95476137,  3970897.88662735,  4174372.75815076,
        3365770.16760058,  3947126.94338174,  5002806.16363892,
        4295941.00885044,  5555095.10063103,  6209121.47338484,
        4988272.24424439,  4237805.33127233,  4063398.29853798,
        4673822.9131082 ,  3583778.95851852,  4237805.33127233,
        3545474.09587838,  3589075.85406197,  1261543.46470608,
        4577756.63238765,  4441280.20279574,  4528483.71916291,
        5278950.63213497,  5714968.21397085,  3409371.92578417,
        4655723.12490375,   796458.04408115,  1314382.24674074,
        1387051.84371339,  2982217.10830167,  3064123.72912539,
         947468.39306759,  2860648.85760198,  3947126.94338174,
         723788.4471085 ,  1241712.6497681 ,  1343450.0855298 ,
        1072602.5125772 ,  2964117.32009722,  4306909.05943505,
        5135342.46492321,  5526027.26184197,  6368994.58672466,
        3209462.92307068,  4063398.29853798,  4543017.63855744,
        4726661.69514287,  4334245.87149058,  3587344.82732844,
        3703616.18248467,  2817047.0994184 ,  2671707.90547311,
        2008444.50886822,  2299122.8967588 ,  3311200.35883239,
        3732684.02127373,  5066238.73676049,  5385984.96344013,
        3311200.35883239,  3732684.02127373,  4706456.62070718,
        5026202.84738683,  4037896.32855884,  7250266.77424748,
        8238573.29307546,  5923739.98103771,  1979376.67007916,
        2095648.02523539,  3035055.89033633,  2991454.13215275,
        3540177.20033493,  3947126.94338174,  5075475.76061156,
        3412937.79459409,  2904250.61578557,  4915602.64727174,
        1892173.15371199,  3254795.7079878 ,  2904250.61578557,
        3078657.64851992,  3035055.89033633,  3340268.19762145,
        4077932.21793251,  4770263.45332645,  4944670.4860608 ,
        1572426.92703234,  1083570.56316181,  1083570.56316181,
        1330647.1928688 ,  1877639.23431746,  1010900.96618916,
        1214375.83771257,  1039968.80497822,  1243443.67650163,
        1243443.67650163,  1693995.17773203,  1083570.56316181,
        1083570.56316181,  1330647.1928688 ,  1659630.44339952,
        1069036.64376728,  1287045.43468521,  1601494.7658214 ,
        1185307.99892351,  1199841.91831804,  1330647.1928688 ,
        1330647.1928688 ,  1272511.51529068,  1790435.71795028,
        1519588.14499768,  3078657.64851992,  4334245.87149058,
         947468.39306759,   947468.39306759,   947468.39306759,
        1261917.72420378,   947468.39306759,  3307634.49002246,
        3060557.86031547,  3572810.90793391,   592983.17255774,
         636584.93074133,   651118.85013586,   869127.64105379,
        1212644.81097904,   322135.59960514,   365737.35778873,
         482008.71294496,   651118.85013586,   781924.12468662,
         781924.12468662,   752856.28589756,   810991.96347568,
         781924.12468662,   840059.80226474,   970865.0768155 ,
        2468233.0339497 ,  2526368.71152781,  3970897.88662735,
        2700775.74426216,  3267598.6006488 ,  2037512.34765728,
        2860648.85760198,  1261917.72420378,  2876913.80373004,
        2353692.70552699,  2962386.29336369,  2328190.73554786,
        2962386.29336369,  2110181.94462992,  2715309.66365669,
        3974463.75543727,  2846114.93820745,  1621699.84025708,
        3078657.64851992,  3442005.63338315,  3005988.05154728,
        4310474.92824497,  1732300.04037216,  4604719.18494548,
        3325734.27822692,  3005988.05154728,  3316497.25437584,
        6706840.60160875,  3005988.05154728,  3005988.05154728,
        1863105.31492293,  2468233.0339497 ,   854593.72165926,
        3005988.05154728,  2400860.3325205 ,  3005988.05154728,
        2400860.3325205 ,  3752889.09570941,  3874457.3464091 ,
        4261576.27451793,  3859923.42701457,  4450517.22664681,
        4479585.06543587,  4697593.85635381,  5206281.03516233,
        3729118.15246381,  3005988.05154728,  3442005.63338315,
        2691538.72041109,  3296666.43943786,  1621699.84025708,
        2691538.72041109,  2691538.72041109,  2691538.72041109,
        2760642.44857381,  2255521.13857521,  3078657.64851992,
        2962386.29336369,  4136067.89551062,  3442005.63338315,
        5278950.63213497,  3990728.70156533,  2673438.93220663,
        2673438.93220663,  4842933.0502991 ,  2933318.45457463,
        2328190.73554786,  1307250.50912089,  2400860.3325205 ,
        2255521.13857521,  3151327.24549257,  2575267.36525485,
        2744377.50244575,  3369336.0364105 , 11416204.74493389,
        8447345.06014233,  6427130.26430278,  4888265.83521621,
        4848229.94584255,  2640430.96510995,  2473529.92949315,
        2328190.73554786,  3005988.05154728,  2255521.13857521,
        1261917.72420378,  1299848.32734621,  3825184.43318436,
        3752889.09570941,  3598312.87791305,   947468.39306759,
        6557935.53885354,   947468.39306759,  2110181.94462992,
        3947126.94338174,   781924.12468662,  2110181.94462992,
        3365770.16760058,  4261576.27451793,  3005988.05154728,
        2473529.92949315,  3005988.05154728,  4731958.59068632,
        3020521.9709418 ,  3078657.64851992,  3005988.05154728,
        2691538.72041109,  2400860.3325205 ,  2473529.92949315,
        3051320.83646439,  2715309.66365669,  2528099.73826134,
        2182851.54160257,  3645480.50490656,  2691538.72041109,
        3680219.49873677,  2691538.72041109,  3296666.43943786,
        2933318.45457463,  4842933.0502991 ,  3005988.05154728,
        4319711.95209605,  2715309.66365669,  3005988.05154728,
        3223996.84246521,  2400860.3325205 ,  2715309.66365669,
        3151327.24549257,  3296666.43943786,  2976920.21275822,
        3051320.83646439,  2715309.66365669,  2715309.66365669,
        2400860.3325205 ,  4319711.95209605,  5322552.39031856,
        4799331.29211551,  4479585.06543587,  3801787.74943645,
        3627380.7167021 ,  2962386.29336369,  2555436.55031687,
        3327465.30496045,  2569970.4697114 ,  4517515.66857831,
        3660014.42430109,  3369336.0364105 ,  3282132.52004333,
        2255521.13857521,  3007719.0782808 ,  2400860.3325205 ,
        2400860.3325205 ,  2642640.06668405,  2715309.66365669,
        2569970.4697114 ,  3151327.24549257,  3075091.77971   ,
        2760642.44857381,  2642640.06668405,  2328190.73554786,
        1621699.84025708,  2715309.66365669,  3151327.24549257,
        2715309.66365669,  2744377.50244575,  3093191.56791445,
        2715309.66365669,  2424631.27576611,  2110181.94462992,
        2110181.94462992,   947468.39306759,  3296666.43943786,
        3078657.64851992,  2400860.3325205 ,  3005988.05154728,
        2715309.66365669,  3078657.64851992,  2255521.13857521,
        1981481.95631039,  2860648.85760198,  4537720.74301399,
        2802513.18002387,  2279292.08182082,  1261917.72420378,
        3035055.89033633,  1261917.72420378,  1528825.16884876,
        3798221.88062653,  2279292.08182082,  2206622.48484817,
         947468.39306759,  1621699.84025708,   278533.84142155,
         636584.93074133,   694720.60831944,   709254.52771397,
         767390.20529209,  1697935.30603965,  1667032.6251742 ,
        4888265.83521621,  1261917.72420378,  1261917.72420378,
        3020521.9709418 ,  2735140.47859468,  2086785.26088202,
        3514675.2303558 ,  1261917.72420378,  1727003.14482871,
        2410097.35637158,  3656448.55549116,  1727003.14482871,
        3442005.63338315,   947468.39306759,  4624924.25938116,
        3805353.61824638,  3801787.74943645,  3801787.74943645,
        2905981.6425191 ,  4741195.61453739,   423873.03536684,
        4377847.62967417,  2255521.13857521,  3078657.64851992,
        3151327.24549257,  4697593.85635381,  3540177.20033493,
        1276451.64359831,  3151327.24549257,  2715309.66365669,
        3078657.64851992,  3005988.05154728,  2860648.85760198,
        2008444.50886822,  4895397.57283606,  3005988.05154728,
        2110181.94462992,  2424631.27576611,  3296666.43943786,
        3272895.49619225,  3632677.61224556,  3127556.30224696,
        3442005.63338315,  3151327.24549257,  3947126.94338174,
        3151327.24549257,  4217974.51633435,  2211919.38039163,
        2860648.85760198,  3412937.79459409,  3500141.31096127,
        3296666.43943786,  1993910.58947369,  3801787.74943645,
        2628106.14728952,  4058101.40299453,  2133952.88787553,
        2715309.66365669,  3005988.05154728,  3854252.27197342,
        3854252.27197342,  3854252.27197342,  2255521.13857521,
        3078657.64851992,  3151327.24549257,  2468233.0339497 ,
        1674164.36279405,  2569970.4697114 ,  2110181.94462992,
        2148486.80727006,  2400860.3325205 ,  3051320.83646439,
        4915602.64727174,  4092466.13732704,  2831581.01881293,
        2168317.62220804,  2110181.94462992,  3979760.65098073,
        6005646.60186143,  4165135.73429968,  2482766.95334423,
        2860648.85760198,  4761026.42947538,  4679494.06814935,
        2993185.15888627,  3120424.56462711,  3369336.0364105 ,
        9493787.25654842,  9493787.25654842,  8926964.40016179,
        7170091.18015729,  9493787.25654842,  9493787.25654842,
        8926964.40016179,  7170091.18015729,  3005988.05154728,
        3369336.0364105 ,  4406915.46846323,  2279292.08182082,
        2831581.01881293,  3296666.43943786,  3103785.35900136,
        1964842.75068463,  2328190.73554786,  1621699.84025708,
        1621699.84025708,  2250598.50252946,  1621699.84025708,
        1621699.84025708,  1621699.84025708,  2250598.50252946,
        3583778.95851852,  3874457.3464091 ,  4116237.08057264,
        3005988.05154728,  4819162.10705349,  3223996.84246521,
        4872000.88908816,  3311200.35883239,  3296666.43943786,
        3845389.50762004,  1645096.52400499,  3016956.10213188,
        3636617.74055318,  3220430.97365529,  1621699.84025708,
       10611168.02319364,  4130770.99996717,  4130770.99996717,
        2546199.5264658 ,  3296666.43943786,  4237805.33127233,
        2618869.12343844,  2400860.3325205 ,  2086411.00138432,
        2182851.54160257,  4092466.13732704,  1621699.84025708,
        2860648.85760198,  3180395.08428163,  3005988.05154728,
        3296666.43943786,  2110181.94462992,  2905981.6425191 ,
        3670982.47488569,  2546199.5264658 ,  2889716.69639104,
        3093191.56791445,  3020521.9709418 ,  2700775.74426216,
        3005988.05154728,  3369336.0364105 ,  2962386.29336369,
        2569970.4697114 ,  1993910.58947369,  1950308.8312901 ,
        3369336.0364105 ,  2546199.5264658 ,  2482766.95334423,
        2802513.18002387,  1964842.75068463,  2313656.81615333,
        2133952.88787553,  1703232.20158311,  1703232.20158311,
        3296666.43943786,  2691538.72041109,  3442005.63338315,
        2400860.3325205 ,  3223996.84246521,  2400860.3325205 ,
        2642640.06668405,  3485607.39156674,  3264032.73183888,
        2517131.68767674,  3627380.7167021 ,  2762477.2906502 ,
        3289534.70181801,  2313656.81615333,  2313656.81615333,
        2691538.72041109,  2197385.4609971 ,  1407256.91814907,
        7075485.48201543,  3151327.24549257,  3272895.49619225,
        2691538.72041109,  2982217.10830167,  2458996.01009862,
        4306909.05943505,  2569970.4697114 ,  4116237.08057264,
        4188906.67754529,  3078657.64851992,  1636233.75965161,
        4406915.46846323,  3438439.76457323,   -41212.38525809,
        2715309.66365669,  2715309.66365669,  5912771.9304531 ,
        3854252.27197342,  4697593.85635381,  4697593.85635381,
        2360232.96925453,  4188906.67754529,  3118693.53789358,
        2400860.3325205 ,  3442005.63338315,  2691538.72041109,
        3511109.36154587,  1261917.72420378,   947468.39306759,
        2860648.85760198,  9620278.14329386,  3816321.66883098,
        3005988.05154728,  3035055.89033633,  3253064.68125427,
        3398403.87519956,  3005988.05154728,  3874457.3464091 ,
        4597587.44732563,  3458270.57951121,  3283863.54677686,
        3151327.24549257,  2802513.18002387,  2947852.37396916,
        3307634.49002246,  3947126.94338174,  4092466.13732704,
        4488447.82978925,  3801787.74943645,  3442005.63338315,
        3660014.42430109,  3700050.31367475,  3456539.55277768,
        5249882.79334591,  4383144.52521762,  2337427.75939894,
        2715309.66365669,  2400860.3325205 ,  3442005.63338315,
        3093191.56791445,  2555436.55031687,  3383869.95580503,
        3656448.55549116,  3656448.55549116,  5424289.82608026,
        3064123.72912539,  4070665.25823524,   -41212.38525809,
        3078657.64851992,  2831581.01881293,  2328190.73554786,
        3005988.05154728,  3020521.9709418 ,  2744377.50244575,
        2569970.4697114 ,  2528099.73826134,  2528099.73826134,
        2528099.73826134,  2528099.73826134,  2760642.44857381,
        2991454.13215275,  4223271.4118778 ,  3104159.61849906,
        5476754.34861723,  3051320.83646439,  3194929.00367615,
        1621699.84025708,  3078657.64851992,  3194929.00367615,
        3485607.39156674,  4528483.71916291,  3801787.74943645,
        2295931.28744658,  1261917.72420378,  1621699.84025708,
        3442005.63338315,   -41212.38525809,  4842933.0502991 ,
        1890816.38647616,  3078657.64851992,  2933318.45457463,
        1621699.84025708,  2575267.36525485,  4165135.73429968,
        4237805.33127233,  1621699.84025708,  4866703.99354471,
        4964501.30099878,  3583778.95851852,   678351.84684852,
        1307250.50912089,  1621699.84025708,  1621699.84025708,
         678351.84684852,  1621699.84025708,  1981481.95631039,
        1621699.84025708,  1261917.72420378,  3136793.32609804,
        3587344.82732844,  4237805.33127233,  4019796.54035439,
        3580213.08970859,  3854252.27197342,  3918059.10459269,
         678351.84684852,  3180395.08428163,  2237421.35037076,
        2277082.98024672,  2565047.83366565,   678351.84684852,
        1936149.17139327,  1936149.17139327,  3282132.52004333,
        2715309.66365669,  1621699.84025708,  3151327.24549257,
        1261917.72420378,   678351.84684852,  3365770.16760058,
        3901794.15846463,  3016956.10213188,  1621699.84025708,
        1621699.84025708,  3947126.94338174,  6034340.18115279,
        1621699.84025708,  2628106.14728952,  4319711.95209605,
         947468.39306759,  2831581.01881293,   947468.39306759,
         947468.39306759,  4595856.4205921 ,  4450517.22664681,
        4005262.62095986,   678351.84684852,  3874457.3464091 ,
        2860648.85760198,  2918784.5351801 ,  1377814.81986231,

In [254]:
result_data = pd.concat([data1.reset_index(), pd.Series(predictions,name='predictions')],axis='columns')
result_data

,index,usable_area,number_of_story,number_of_bedroom,number_of_bathroom,number_of_parking,sell_price,predictions
0,0,185.0,2.0,4.0,4.0,4.0,3950000.0,4.624924e+06
1,1,165.0,2.0,4.0,4.0,4.0,3250000.0,4.334246e+06
2,2,260.0,2.0,4.0,4.0,4.0,6300000.0,5.714968e+06
3,3,343.0,2.0,6.0,6.0,6.0,6900000.0,7.550182e+06
4,4,223.0,2.0,4.0,4.0,4.0,4490000.0,5.177213e+06
...,...,...,...,...,...,...,...,...
988,988,120.0,1.0,3.0,3.0,3.0,1990000.0,3.005988e+06
989,989,96.0,1.0,2.0,2.0,2.0,1390000.0,2.342725e+06
990,990,100.0,1.0,3.0,3.0,3.0,1990000.0,2.715310e+06
991,991,0.0,2.0,2.0,2.0,2.0,1850000.0,1.307251e+06
992,992,138.0,1.0,3.0,3.0,3.0,2490000.0,3.267599e+06

In [256]:

from sklearn.metrics import mean_squared_error
  
# Calculation of Mean Squared Error (MSE)
mean_squared_error(y,predictions)

4117544989177.401

In [257]:
from sklearn import metrics
metrics.mean_absolute_error(y, predictions)

1063650.1337993094